version: '3.9'
services:
  pia:
    image: qmcgaw/gluetun
    container_name: pia
    init: true
    cap_add:
      - NET_ADMIN
    env_file:
      - .env
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - SERVER_REGIONS=Netherlands
      - FIREWALL_OUTBOUND_SUBNETS=192.168.4.0/22
      - OPENVPN_PROTOCOL=tcp
      - PRIVATE_INTERNET_ACCESS_OPENVPN_ENCRYPTION_PRESET=normal
      - HTTPPROXY=off
      - SHADOWSOCKS=off
    ports:
      - 8000:80/tcp
  rtorrent:
    environment:
      - USR_ID=1000
      - GRP_ID=1000
    image: diameter/rtorrent-rutorrent:latest
    container_name: rtorrent
    network_mode: "service:pia"
    volumes:
      - /tank/media/Downloads:/downloads
